---
title: "STAT_Proj"
author: "Balaji Kumar, bzk18"
date: "4/20/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
cat("\f")
rm(list=ls())
if(dev.cur()>1) dev.off()
library(ggplot2)
library(colorRamps)
library(plotly)
library(gridExtra)
```

```{r beale}
#Beale function is in domain [-4.5,4.5] for both x and y axes. Global min is at (3, 0.5)
beale <- function(x){
  x1 = x[1]
  x2 = x[2]
  y <- (1.5 - x1 + x1*x2)^2 +(2.25 - x1 + x1*x2^2)^2 +(2.625 - x1 + x1*x2^3)^2
  return(y)
}

#Stochastic Gradient Descent algorithm with momentum
momentum <- function(theta_init,step=.1,eps=1e-4,tol=1e-3,gamma=0.9){
  thetas = matrix(NA,nrow=1000,ncol=2)
  fs = rep(NA,1000)
  dfs = matrix(NA,1000,2)
  fs = rep(NA,1000)
  x = as.vector(theta_init)
  f.x = beale(x)
  fs[1] = f.x
  f.x.plus.eps = c(beale(x+c(eps,0)), beale(x+c(0,eps)))
  df.x =  (f.x.plus.eps - f.x)/eps
  thetas[1,] = theta_init
  dfs[1,] = df.x
  count=1
  prev.update = 0
  while(1){
    x = thetas[count,]
    f.x = fs[count]
    df.x = dfs[count,] 
    count= count+1
    # print(count)
    x.new = x - gamma*prev.update- step*df.x
    prev.update = x-x.new
    thetas[count,] = x.new
    f.x = beale(x.new)
    fs[count] = f.x
    f.x.plus.eps = c(beale(x.new+c(eps,0)), beale(x.new+c(0,eps)))
    df.x =  (f.x.plus.eps - f.x)/eps
    if(any(!is.finite(df.x))) break
    dfs[count,] = df.x
    if(count%%1000==0){
      fs = c(fs,rep(NA,1000))
      dfs = rbind(dfs,matrix(NA,1000,2))
      thetas = rbind(thetas,matrix(NA,nrow=1000,ncol=2))
    }
    if(abs(fs[count]-fs[count-1])<tol) break
    if(count==10000) break
  }
  thetas = na.omit(thetas)
  attributes(thetas)$na.action = NULL
  fs = as.vector(na.omit(fs))
  dfs = na.omit(dfs)
  attributes(dfs)$na.action = NULL
  return (data.frame("thetas"=thetas,"fs"=fs,"dfs"= dfs))
}


t1 = Sys.time()
x.in=c(-3,-3)
Final.res = momentum(x.in)
mom.res = Final.res
print("Momentum res:")
print(tail(mom.res,1))
t2 = Sys.time()
#print(t2-t1)
df = mom.res
colnames(df) = c("Beta1","Beta2","Fx","dfx1","dfx2")
plots=list()
plots[[1]] = ggplot(df,aes(1:nrow(df),Fx))+geom_point()+geom_line()+xlab("i")+ylab("f(x)")+theme_classic()
plots[[2]] = ggplot(df,aes(1:nrow(df),dfx1))+geom_point()+geom_line()+xlab("i")+ylab("f'(x1)")+theme_classic()
plots[[3]] = ggplot(df,aes(1:nrow(df),dfx2))+geom_point()+geom_line()+xlab("i")+ylab("f'(x2)")+theme_classic()
grid.arrange(grobs=plots,nrow=1,ncol=3)

```

